POST http://localhost:5012/api/voter/uvcCodes
Content-Type: application/json

{
  "uvcCode": "WL3K3YPT"
}

###
GET http://localhost:5001/api/voter

###
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
  "emailId": "pishon@test.com",
  "password": "test",
  "name": "Pishon",
  "role": "Admin"
}

###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "password": "test",
  "emailId":"pishon@test.com"
}

###
POST http://localhost:5001/api/topic/add-topic
Content-Type: "application/json"

{
  "topic": "test topic",
  "details": "test topic description is very large",
  "supervisor": "test",
  "isCustom": false
}

###
GET http://localhost:5001/api/admin/election-status
Content-Type: "application/json"
x-auth-token: eyJhbGciOiJIUzI9NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWExNjg1YzcyNTFlMWI1OTgxNzI1OGIiLCJpYXQiOjE3MDUxNjAzMTUsImV4cCI6MTcwNTI0NjcxNX0.YFgLNaK5hPU3CWCmidZpViVlKFIHafHcbwNweDT38ME

###
GET http://localhost:5001/api/voter/candidate
Content-Type: "application/json"
x-auth-token: eyJhbGciOiJIUzI-12NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWExNjg1YzcyNTFlMWI1OTgxNzI1OGIiLCJpYXQiOjE3MDUxNzQ4OTIsImV4cCI6MTcwNTI2MTI5Mn0.s6Xoo40vLZ6sdWUZzonBbpP7vCBotEBQ_l3Ig_Ru8Yo

###
GET http://localhost:5001/api/topic/assign-topic
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjA3YzIwYTJhMDlmNTNlODhjOWYyOTciLCJpYXQiOjE3MTQwNTYwNzcsImV4cCI6MTcxNDE0MjQ3N30.0sKhsn15XvaqacWnehy36Y6afgYEnRgyKXKAKtISsoI