POST http://localhost:5001/api/voter/uvcCodes
Content-Type: application/json

{
  "uvcCode": "WL3K3YPT"
}

###
GET http://localhost:5001/api/voter

###
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
  "voterId": "election@shangrila.gov.sr",
  "password": "shangrila2024$"
}

###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "password": "test",
    "voterId":"pishon@test.com"
}

###
POST http://localhost:5001/api/voter/candidate
Content-Type: "application/json"

{
   "candidate": "b1c1",
   "party": "Blue Party",
   "constituency": "Shangri-la-Town"

}

###
POST http://localhost:5001/api/voter/party
Content-Type: "application/json"

{
    "party": "Blue Party"
}

###
GET http://localhost:5001/api/admin/election-status
Content-Type: "application/json"
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWExNjg1YzcyNTFlMWI1OTgxNzI1OGIiLCJpYXQiOjE3MDUxNjAzMTUsImV4cCI6MTcwNTI0NjcxNX0.YFgLNaK5hPU3CWCmidZpViVlKFIHafHcbwNweDT38ME

###
GET http://localhost:5001/api/voter/candidate
Content-Type: "application/json"
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWExNjg1YzcyNTFlMWI1OTgxNzI1OGIiLCJpYXQiOjE3MDUxNzQ4OTIsImV4cCI6MTcwNTI2MTI5Mn0.s6Xoo40vLZ6sdWUZzonBbpP7vCBotEBQ_l3Ig_Ru8Yo